version: '3.9'

services:
  php:
    image: php:fpm-alpine
    restart: unless-stopped
    env_file: .env
    environment:
      - ACCESS_KEY_HASH=$ACCESS_KEY_HASH
    volumes:
      - www-html:/var/www/html
    networks:
      - app

  nginx:
    image: nginx:1.19.8-alpine
    depends_on:
      - wp
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - www-html:/var/www/html
      - ./nginx-conf.d:/etc/nginx/conf.d
      - etc-letsencrypt:/etc/letsencrypt
    networks:
      - app

  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    container_name: certbot
    volumes:
      - etc-letsencrypt:/etc/letsencrypt
      - www-html:/var/www/html
 
volumes:
  www-html:
  dbfile:
  etc-letsencrypt:

networks:
  app:
    driver: bridge

